-- License Plate Recognition System Database Schema
-- Run this SQL in your Supabase SQL Editor

-- Create the license_plates table
CREATE TABLE IF NOT EXISTS license_plates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR(20) NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    confidence_score FLOAT,
    image_path VARCHAR(255),
    camera_location VARCHAR(100)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_plate_number ON license_plates(plate_number);
CREATE INDEX IF NOT EXISTS idx_timestamp ON license_plates(timestamp);

-- Enable Row Level Security (RLS) for better security
ALTER TABLE license_plates ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all operations (for development)
-- In production, you might want more restrictive policies
CREATE POLICY "Enable all operations for all users" ON license_plates
    FOR ALL USING (true) WITH CHECK (true);

-- Optional: Create a view for recent plates
CREATE OR REPLACE VIEW recent_plates AS
SELECT 
    plate_number,
    timestamp,
    camera_location,
    confidence_score
FROM license_plates 
ORDER BY timestamp DESC 
LIMIT 100;

-- Grant access to the view
GRANT SELECT ON recent_plates TO anon;
GRANT SELECT ON recent_plates TO authenticated;
