from supabase import create_client, Client
import os
from dotenv import load_dotenv

load_dotenv()

def create_supabase_table():
    """Create the license_plates table in Supabase"""
    try:
        # Initialize Supabase client
        supabase: Client = create_client(
            os.getenv('SUPABASE_URL'),
            os.getenv('SUPABASE_KEY')
        )
        
        # SQL to create the table
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS license_plates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            plate_number VARCHAR(20) NOT NULL,
            timestamp TIMESTAMPTZ DEFAULT NOW(),
            confidence_score FLOAT,
            image_path VARCHAR(255),
            camera_location VARCHAR(100)
        );
        
        -- Create index for faster queries
        CREATE INDEX IF NOT EXISTS idx_plate_number ON license_plates(plate_number);
        CREATE INDEX IF NOT EXISTS idx_timestamp ON license_plates(timestamp);
        """
        
        # Execute the SQL using Supabase SQL editor or directly via RPC
        # Note: This SQL should be run in Supabase SQL editor manually
        # or you can use Supabase client to execute it if permissions allow
        
        print("Table creation SQL generated:")
        print(create_table_sql)
        print("\nPlease run this SQL in your Supabase SQL editor:")
        print("1. Go to your Supabase project")
        print("2. Click on 'SQL Editor' in the sidebar")
        print("3. Create a new query and paste the SQL above")
        print("4. Run the query to create the table")
        
        # Test connection
        try:
            # Try to access the table to verify connection
            result = supabase.table('license_plates').select('id').limit(1).execute()
            print("✓ Successfully connected to Supabase and table exists!")
            return True
        except Exception as e:
            if "does not exist" in str(e):
                print("⚠ Table doesn't exist yet. Please run the SQL above first.")
            else:
                print(f"✗ Connection error: {e}")
            return False
            
    except Exception as e:
        print(f"Error setting up Supabase: {e}")
        return False

def test_supabase_connection():
    """Test the Supabase connection"""
    try:
        supabase: Client = create_client(
            os.getenv('SUPABASE_URL'),
            os.getenv('SUPABASE_KEY')
        )
        
        # Test basic connection
        result = supabase.table('license_plates').select('count').execute()
        print("✓ Supabase connection successful!")
        return True
        
    except Exception as e:
        print(f"✗ Supabase connection failed: {e}")
        return False

if __name__ == "__main__":
    print("Setting up Supabase for LPR System...")
    create_supabase_table()
    
    print("\nTesting connection...")
    test_supabase_connection()
